/********************************************************************************
** Form generated from reading UI file 'tractionpage.ui'
**
** Created: Thu Jan 11 11:16:18 2018
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TRACTIONPAGE_H
#define UI_TRACTIONPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_TractionPage
{
public:
    QLabel *label_car1safety;
    QLabel *label_car4No;
    QLabel *label_car2lineCurr1;
    QLabel *label_car4AllBrakeRelease;
    QLabel *label_HSCB;
    QLabel *label_car1EBEffect;
    QLabel *label_car3lineCurr2;
    QLabel *label_car2HSCB;
    QLabel *label_EBEffect;
    QLabel *label_vehicleNo;
    QLabel *label_car3No;
    QLabel *label_safetyBrake;
    QLabel *label_car4lineCurr;
    QLabel *label_car1inverterCurr;
    QLabel *label_car1No;
    QLabel *label_car4EBState;
    QLabel *label_car1lineCurr;
    QLabel *label_inverterCurr;
    QLabel *label_car2No;
    QLabel *label_car1HSCB;
    QLabel *label_lineCurr;
    QLabel *label_EBState;
    QPushButton *btn_EmergencyBroadcast;
    QLabel *label_car4HSCB;
    QLabel *label_allBrakeRelease;
    QLabel *label_car4inverterCurr;
    QLabel *label_car1EBState;
    QLabel *label_car4safety;
    QLabel *label_car4EBEffect;
    QLabel *label_car3HSCB;
    QLabel *label_car1AllBrakeRelease;
    QLabel *label_car4Contactor;
    QLabel *label_car1Contactor;
    QLabel *label_contactor;
    QLabel *label_car2Contactor1;
    QLabel *label_car2Contactor2;
    QLabel *label_car3Contactor1;
    QLabel *label_car3Contactor2;
    QLabel *label_car4chargeContactor;
    QLabel *label_chargeContactor;
    QLabel *label_car3chargeContactor2;
    QLabel *label_car2chargeContactor1;
    QLabel *label_car1chargeContactor;
    QLabel *label_car2chargeContactor2;
    QLabel *label_car3chargeContactor1;
    QLabel *label_car3lineCurr1;
    QLabel *label_car2lineCurr2;
    QLabel *label_car2AllBR1;
    QLabel *label_car2AllBR2;
    QLabel *label_car2AllBR3;
    QLabel *label_car2AllBR4;
    QLabel *label_car3AllBR4;
    QLabel *label_car3AllBR3;
    QLabel *label_car3AllBR2;
    QLabel *label_car3AllBR1;
    QLabel *label_car3EBState1;
    QLabel *label_car2EBState1;
    QLabel *label_car2EBState3;
    QLabel *label_car2EBState2;
    QLabel *label_car2EBState4;
    QLabel *label_car3EBState4;
    QLabel *label_car3EBState2;
    QLabel *label_car3EBState3;
    QLabel *label_car4tractionAllowed;
    QLabel *label_car2tractionAllowed;
    QLabel *label_car1tractionAllowed;
    QLabel *label_car3tractionAllowed;
    QLabel *label_tractionAllowed;
    QLabel *label_car3safety1;
    QLabel *label_car2safety2;
    QLabel *label_car2safety3;
    QLabel *label_car3safety4;
    QLabel *label_car3safety3;
    QLabel *label_car2safety4;
    QLabel *label_car3safety2;
    QLabel *label_car2safety1;
    QLabel *label_car3inverterCurr1;
    QLabel *label_car2inverterCurr3;
    QLabel *label_car2inverterCurr1;
    QLabel *label_car2inverterCurr4;
    QLabel *label_car3inverterCurr2;
    QLabel *label_car2inverterCurr2;
    QLabel *label_car3inverterCurr3;
    QLabel *label_car3inverterCurr4;
    QLabel *label_car3EBEffect1;
    QLabel *label_car2EBEffect2;
    QLabel *label_car3EBEffect3;
    QLabel *label_car3EBEffect2;
    QLabel *label_car2EBEffect1;
    QLabel *label_car2EBEffect3;
    QLabel *label_car3EBEffect4;
    QLabel *label_car2EBEffect4;
    QLabel *label_car2IsolateState4;
    QLabel *label_car4IsolateState;
    QLabel *label_car3IsolateState2;
    QLabel *label_isolateState;
    QLabel *label_car3IsolateState1;
    QLabel *label_car1IsolateState;
    QLabel *label_car2IsolateState2;
    QLabel *label_car2IsolateState3;
    QLabel *label_car3IsolateState3;
    QLabel *label_car2IsolateState1;
    QLabel *label_car3IsolateState4;

    void setupUi(QWidget *TractionPage)
    {
        if (TractionPage->objectName().isEmpty())
            TractionPage->setObjectName(QString::fromUtf8("TractionPage"));
        TractionPage->resize(1024, 618);
        TractionPage->setStyleSheet(QString::fromUtf8("QLabel\n"
"{\n"
"	color: white;\n"
"	border: 2px groove, gray;\n"
"    border-color: gray;\n"
"	font: 17px, \"SimHei\";	\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"	background-color: black;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"	font: 20px, \"SimHei\";\n"
"    color: black;\n"
"	background-color: rgb(250, 250, 250);\n"
"	border-radius: 5px;\n"
"}"));
        label_car1safety = new QLabel(TractionPage);
        label_car1safety->setObjectName(QString::fromUtf8("label_car1safety"));
        label_car1safety->setGeometry(QRect(149, 286, 187, 35));
        label_car1safety->setAlignment(Qt::AlignCenter);
        label_car4No = new QLabel(TractionPage);
        label_car4No->setObjectName(QString::fromUtf8("label_car4No"));
        label_car4No->setGeometry(QRect(753, 112, 180, 35));
        label_car4No->setAlignment(Qt::AlignCenter);
        label_car2lineCurr1 = new QLabel(TractionPage);
        label_car2lineCurr1->setObjectName(QString::fromUtf8("label_car2lineCurr1"));
        label_car2lineCurr1->setGeometry(QRect(335, 320, 105, 35));
        label_car2lineCurr1->setAlignment(Qt::AlignCenter);
        label_car4AllBrakeRelease = new QLabel(TractionPage);
        label_car4AllBrakeRelease->setObjectName(QString::fromUtf8("label_car4AllBrakeRelease"));
        label_car4AllBrakeRelease->setGeometry(QRect(753, 217, 180, 35));
        label_car4AllBrakeRelease->setAlignment(Qt::AlignCenter);
        label_HSCB = new QLabel(TractionPage);
        label_HSCB->setObjectName(QString::fromUtf8("label_HSCB"));
        label_HSCB->setGeometry(QRect(10, 182, 140, 35));
        label_car1EBEffect = new QLabel(TractionPage);
        label_car1EBEffect->setObjectName(QString::fromUtf8("label_car1EBEffect"));
        label_car1EBEffect->setGeometry(QRect(149, 388, 187, 35));
        label_car1EBEffect->setAlignment(Qt::AlignCenter);
        label_car3lineCurr2 = new QLabel(TractionPage);
        label_car3lineCurr2->setObjectName(QString::fromUtf8("label_car3lineCurr2"));
        label_car3lineCurr2->setGeometry(QRect(544, 320, 105, 35));
        label_car3lineCurr2->setAlignment(Qt::AlignCenter);
        label_car2HSCB = new QLabel(TractionPage);
        label_car2HSCB->setObjectName(QString::fromUtf8("label_car2HSCB"));
        label_car2HSCB->setGeometry(QRect(335, 182, 210, 35));
        label_car2HSCB->setAlignment(Qt::AlignCenter);
        label_EBEffect = new QLabel(TractionPage);
        label_EBEffect->setObjectName(QString::fromUtf8("label_EBEffect"));
        label_EBEffect->setGeometry(QRect(10, 388, 140, 35));
        label_vehicleNo = new QLabel(TractionPage);
        label_vehicleNo->setObjectName(QString::fromUtf8("label_vehicleNo"));
        label_vehicleNo->setGeometry(QRect(10, 112, 140, 35));
        label_car3No = new QLabel(TractionPage);
        label_car3No->setObjectName(QString::fromUtf8("label_car3No"));
        label_car3No->setGeometry(QRect(544, 112, 210, 35));
        label_car3No->setAlignment(Qt::AlignCenter);
        label_safetyBrake = new QLabel(TractionPage);
        label_safetyBrake->setObjectName(QString::fromUtf8("label_safetyBrake"));
        label_safetyBrake->setGeometry(QRect(10, 286, 140, 35));
        label_car4lineCurr = new QLabel(TractionPage);
        label_car4lineCurr->setObjectName(QString::fromUtf8("label_car4lineCurr"));
        label_car4lineCurr->setGeometry(QRect(753, 320, 180, 35));
        label_car4lineCurr->setAlignment(Qt::AlignCenter);
        label_car1inverterCurr = new QLabel(TractionPage);
        label_car1inverterCurr->setObjectName(QString::fromUtf8("label_car1inverterCurr"));
        label_car1inverterCurr->setGeometry(QRect(149, 354, 187, 35));
        label_car1inverterCurr->setAlignment(Qt::AlignCenter);
        label_car1No = new QLabel(TractionPage);
        label_car1No->setObjectName(QString::fromUtf8("label_car1No"));
        label_car1No->setGeometry(QRect(149, 112, 187, 35));
        label_car1No->setScaledContents(false);
        label_car1No->setAlignment(Qt::AlignCenter);
        label_car4EBState = new QLabel(TractionPage);
        label_car4EBState->setObjectName(QString::fromUtf8("label_car4EBState"));
        label_car4EBState->setGeometry(QRect(753, 252, 180, 35));
        label_car4EBState->setAlignment(Qt::AlignCenter);
        label_car1lineCurr = new QLabel(TractionPage);
        label_car1lineCurr->setObjectName(QString::fromUtf8("label_car1lineCurr"));
        label_car1lineCurr->setGeometry(QRect(149, 320, 187, 35));
        label_car1lineCurr->setAlignment(Qt::AlignCenter);
        label_inverterCurr = new QLabel(TractionPage);
        label_inverterCurr->setObjectName(QString::fromUtf8("label_inverterCurr"));
        label_inverterCurr->setGeometry(QRect(10, 354, 140, 35));
        label_car2No = new QLabel(TractionPage);
        label_car2No->setObjectName(QString::fromUtf8("label_car2No"));
        label_car2No->setGeometry(QRect(335, 112, 210, 35));
        label_car2No->setAlignment(Qt::AlignCenter);
        label_car1HSCB = new QLabel(TractionPage);
        label_car1HSCB->setObjectName(QString::fromUtf8("label_car1HSCB"));
        label_car1HSCB->setGeometry(QRect(149, 182, 187, 35));
        label_car1HSCB->setAlignment(Qt::AlignCenter);
        label_lineCurr = new QLabel(TractionPage);
        label_lineCurr->setObjectName(QString::fromUtf8("label_lineCurr"));
        label_lineCurr->setGeometry(QRect(10, 320, 140, 35));
        label_EBState = new QLabel(TractionPage);
        label_EBState->setObjectName(QString::fromUtf8("label_EBState"));
        label_EBState->setGeometry(QRect(10, 252, 140, 35));
        btn_EmergencyBroadcast = new QPushButton(TractionPage);
        btn_EmergencyBroadcast->setObjectName(QString::fromUtf8("btn_EmergencyBroadcast"));
        btn_EmergencyBroadcast->setGeometry(QRect(860, 560, 130, 40));
        label_car4HSCB = new QLabel(TractionPage);
        label_car4HSCB->setObjectName(QString::fromUtf8("label_car4HSCB"));
        label_car4HSCB->setGeometry(QRect(753, 182, 180, 35));
        label_car4HSCB->setAlignment(Qt::AlignCenter);
        label_allBrakeRelease = new QLabel(TractionPage);
        label_allBrakeRelease->setObjectName(QString::fromUtf8("label_allBrakeRelease"));
        label_allBrakeRelease->setGeometry(QRect(10, 217, 140, 35));
        label_car4inverterCurr = new QLabel(TractionPage);
        label_car4inverterCurr->setObjectName(QString::fromUtf8("label_car4inverterCurr"));
        label_car4inverterCurr->setGeometry(QRect(753, 354, 180, 35));
        label_car4inverterCurr->setAlignment(Qt::AlignCenter);
        label_car1EBState = new QLabel(TractionPage);
        label_car1EBState->setObjectName(QString::fromUtf8("label_car1EBState"));
        label_car1EBState->setGeometry(QRect(149, 252, 187, 35));
        label_car1EBState->setAlignment(Qt::AlignCenter);
        label_car4safety = new QLabel(TractionPage);
        label_car4safety->setObjectName(QString::fromUtf8("label_car4safety"));
        label_car4safety->setGeometry(QRect(753, 286, 180, 35));
        label_car4safety->setAlignment(Qt::AlignCenter);
        label_car4EBEffect = new QLabel(TractionPage);
        label_car4EBEffect->setObjectName(QString::fromUtf8("label_car4EBEffect"));
        label_car4EBEffect->setGeometry(QRect(753, 388, 180, 35));
        label_car4EBEffect->setAlignment(Qt::AlignCenter);
        label_car3HSCB = new QLabel(TractionPage);
        label_car3HSCB->setObjectName(QString::fromUtf8("label_car3HSCB"));
        label_car3HSCB->setGeometry(QRect(544, 182, 210, 35));
        label_car3HSCB->setAlignment(Qt::AlignCenter);
        label_car1AllBrakeRelease = new QLabel(TractionPage);
        label_car1AllBrakeRelease->setObjectName(QString::fromUtf8("label_car1AllBrakeRelease"));
        label_car1AllBrakeRelease->setGeometry(QRect(149, 217, 187, 35));
        label_car1AllBrakeRelease->setAlignment(Qt::AlignCenter);
        label_car4Contactor = new QLabel(TractionPage);
        label_car4Contactor->setObjectName(QString::fromUtf8("label_car4Contactor"));
        label_car4Contactor->setGeometry(QRect(753, 422, 180, 35));
        label_car4Contactor->setAlignment(Qt::AlignCenter);
        label_car1Contactor = new QLabel(TractionPage);
        label_car1Contactor->setObjectName(QString::fromUtf8("label_car1Contactor"));
        label_car1Contactor->setGeometry(QRect(149, 422, 187, 35));
        label_car1Contactor->setAlignment(Qt::AlignCenter);
        label_contactor = new QLabel(TractionPage);
        label_contactor->setObjectName(QString::fromUtf8("label_contactor"));
        label_contactor->setGeometry(QRect(10, 422, 140, 35));
        label_car2Contactor1 = new QLabel(TractionPage);
        label_car2Contactor1->setObjectName(QString::fromUtf8("label_car2Contactor1"));
        label_car2Contactor1->setGeometry(QRect(335, 422, 105, 35));
        label_car2Contactor1->setAlignment(Qt::AlignCenter);
        label_car2Contactor2 = new QLabel(TractionPage);
        label_car2Contactor2->setObjectName(QString::fromUtf8("label_car2Contactor2"));
        label_car2Contactor2->setGeometry(QRect(440, 422, 105, 35));
        label_car2Contactor2->setAlignment(Qt::AlignCenter);
        label_car3Contactor1 = new QLabel(TractionPage);
        label_car3Contactor1->setObjectName(QString::fromUtf8("label_car3Contactor1"));
        label_car3Contactor1->setGeometry(QRect(649, 422, 105, 35));
        label_car3Contactor1->setAlignment(Qt::AlignCenter);
        label_car3Contactor2 = new QLabel(TractionPage);
        label_car3Contactor2->setObjectName(QString::fromUtf8("label_car3Contactor2"));
        label_car3Contactor2->setGeometry(QRect(544, 422, 105, 35));
        label_car3Contactor2->setAlignment(Qt::AlignCenter);
        label_car4chargeContactor = new QLabel(TractionPage);
        label_car4chargeContactor->setObjectName(QString::fromUtf8("label_car4chargeContactor"));
        label_car4chargeContactor->setGeometry(QRect(753, 456, 180, 35));
        label_car4chargeContactor->setAlignment(Qt::AlignCenter);
        label_chargeContactor = new QLabel(TractionPage);
        label_chargeContactor->setObjectName(QString::fromUtf8("label_chargeContactor"));
        label_chargeContactor->setGeometry(QRect(10, 456, 140, 35));
        label_car3chargeContactor2 = new QLabel(TractionPage);
        label_car3chargeContactor2->setObjectName(QString::fromUtf8("label_car3chargeContactor2"));
        label_car3chargeContactor2->setGeometry(QRect(544, 456, 105, 35));
        label_car3chargeContactor2->setAlignment(Qt::AlignCenter);
        label_car2chargeContactor1 = new QLabel(TractionPage);
        label_car2chargeContactor1->setObjectName(QString::fromUtf8("label_car2chargeContactor1"));
        label_car2chargeContactor1->setGeometry(QRect(335, 456, 105, 35));
        label_car2chargeContactor1->setAlignment(Qt::AlignCenter);
        label_car1chargeContactor = new QLabel(TractionPage);
        label_car1chargeContactor->setObjectName(QString::fromUtf8("label_car1chargeContactor"));
        label_car1chargeContactor->setGeometry(QRect(149, 456, 187, 35));
        label_car1chargeContactor->setAlignment(Qt::AlignCenter);
        label_car2chargeContactor2 = new QLabel(TractionPage);
        label_car2chargeContactor2->setObjectName(QString::fromUtf8("label_car2chargeContactor2"));
        label_car2chargeContactor2->setGeometry(QRect(440, 456, 105, 35));
        label_car2chargeContactor2->setAlignment(Qt::AlignCenter);
        label_car3chargeContactor1 = new QLabel(TractionPage);
        label_car3chargeContactor1->setObjectName(QString::fromUtf8("label_car3chargeContactor1"));
        label_car3chargeContactor1->setGeometry(QRect(649, 456, 105, 35));
        label_car3chargeContactor1->setAlignment(Qt::AlignCenter);
        label_car3lineCurr1 = new QLabel(TractionPage);
        label_car3lineCurr1->setObjectName(QString::fromUtf8("label_car3lineCurr1"));
        label_car3lineCurr1->setGeometry(QRect(649, 320, 105, 35));
        label_car3lineCurr1->setAlignment(Qt::AlignCenter);
        label_car2lineCurr2 = new QLabel(TractionPage);
        label_car2lineCurr2->setObjectName(QString::fromUtf8("label_car2lineCurr2"));
        label_car2lineCurr2->setGeometry(QRect(440, 320, 105, 35));
        label_car2lineCurr2->setAlignment(Qt::AlignCenter);
        label_car2AllBR1 = new QLabel(TractionPage);
        label_car2AllBR1->setObjectName(QString::fromUtf8("label_car2AllBR1"));
        label_car2AllBR1->setGeometry(QRect(335, 217, 52, 35));
        label_car2AllBR1->setAlignment(Qt::AlignCenter);
        label_car2AllBR2 = new QLabel(TractionPage);
        label_car2AllBR2->setObjectName(QString::fromUtf8("label_car2AllBR2"));
        label_car2AllBR2->setGeometry(QRect(387, 217, 52, 35));
        label_car2AllBR2->setAlignment(Qt::AlignCenter);
        label_car2AllBR3 = new QLabel(TractionPage);
        label_car2AllBR3->setObjectName(QString::fromUtf8("label_car2AllBR3"));
        label_car2AllBR3->setGeometry(QRect(439, 217, 52, 35));
        label_car2AllBR3->setAlignment(Qt::AlignCenter);
        label_car2AllBR4 = new QLabel(TractionPage);
        label_car2AllBR4->setObjectName(QString::fromUtf8("label_car2AllBR4"));
        label_car2AllBR4->setGeometry(QRect(491, 217, 53, 35));
        label_car2AllBR4->setAlignment(Qt::AlignCenter);
        label_car3AllBR4 = new QLabel(TractionPage);
        label_car3AllBR4->setObjectName(QString::fromUtf8("label_car3AllBR4"));
        label_car3AllBR4->setGeometry(QRect(544, 217, 52, 35));
        label_car3AllBR4->setAlignment(Qt::AlignCenter);
        label_car3AllBR3 = new QLabel(TractionPage);
        label_car3AllBR3->setObjectName(QString::fromUtf8("label_car3AllBR3"));
        label_car3AllBR3->setGeometry(QRect(596, 217, 52, 35));
        label_car3AllBR3->setAlignment(Qt::AlignCenter);
        label_car3AllBR2 = new QLabel(TractionPage);
        label_car3AllBR2->setObjectName(QString::fromUtf8("label_car3AllBR2"));
        label_car3AllBR2->setGeometry(QRect(648, 217, 52, 35));
        label_car3AllBR2->setAlignment(Qt::AlignCenter);
        label_car3AllBR1 = new QLabel(TractionPage);
        label_car3AllBR1->setObjectName(QString::fromUtf8("label_car3AllBR1"));
        label_car3AllBR1->setGeometry(QRect(700, 217, 53, 35));
        label_car3AllBR1->setAlignment(Qt::AlignCenter);
        label_car3EBState1 = new QLabel(TractionPage);
        label_car3EBState1->setObjectName(QString::fromUtf8("label_car3EBState1"));
        label_car3EBState1->setGeometry(QRect(700, 252, 53, 35));
        label_car3EBState1->setAlignment(Qt::AlignCenter);
        label_car2EBState1 = new QLabel(TractionPage);
        label_car2EBState1->setObjectName(QString::fromUtf8("label_car2EBState1"));
        label_car2EBState1->setGeometry(QRect(335, 252, 52, 35));
        label_car2EBState1->setStyleSheet(QString::fromUtf8(""));
        label_car2EBState1->setAlignment(Qt::AlignCenter);
        label_car2EBState3 = new QLabel(TractionPage);
        label_car2EBState3->setObjectName(QString::fromUtf8("label_car2EBState3"));
        label_car2EBState3->setGeometry(QRect(439, 252, 52, 35));
        label_car2EBState3->setAlignment(Qt::AlignCenter);
        label_car2EBState2 = new QLabel(TractionPage);
        label_car2EBState2->setObjectName(QString::fromUtf8("label_car2EBState2"));
        label_car2EBState2->setGeometry(QRect(387, 252, 52, 35));
        label_car2EBState2->setAlignment(Qt::AlignCenter);
        label_car2EBState4 = new QLabel(TractionPage);
        label_car2EBState4->setObjectName(QString::fromUtf8("label_car2EBState4"));
        label_car2EBState4->setGeometry(QRect(491, 252, 53, 35));
        label_car2EBState4->setAlignment(Qt::AlignCenter);
        label_car3EBState4 = new QLabel(TractionPage);
        label_car3EBState4->setObjectName(QString::fromUtf8("label_car3EBState4"));
        label_car3EBState4->setGeometry(QRect(544, 252, 52, 35));
        label_car3EBState4->setAlignment(Qt::AlignCenter);
        label_car3EBState2 = new QLabel(TractionPage);
        label_car3EBState2->setObjectName(QString::fromUtf8("label_car3EBState2"));
        label_car3EBState2->setGeometry(QRect(648, 252, 52, 35));
        label_car3EBState2->setAlignment(Qt::AlignCenter);
        label_car3EBState3 = new QLabel(TractionPage);
        label_car3EBState3->setObjectName(QString::fromUtf8("label_car3EBState3"));
        label_car3EBState3->setGeometry(QRect(596, 252, 52, 35));
        label_car3EBState3->setAlignment(Qt::AlignCenter);
        label_car4tractionAllowed = new QLabel(TractionPage);
        label_car4tractionAllowed->setObjectName(QString::fromUtf8("label_car4tractionAllowed"));
        label_car4tractionAllowed->setGeometry(QRect(753, 147, 180, 35));
        label_car4tractionAllowed->setAlignment(Qt::AlignCenter);
        label_car2tractionAllowed = new QLabel(TractionPage);
        label_car2tractionAllowed->setObjectName(QString::fromUtf8("label_car2tractionAllowed"));
        label_car2tractionAllowed->setGeometry(QRect(336, 147, 210, 35));
        label_car2tractionAllowed->setAlignment(Qt::AlignCenter);
        label_car1tractionAllowed = new QLabel(TractionPage);
        label_car1tractionAllowed->setObjectName(QString::fromUtf8("label_car1tractionAllowed"));
        label_car1tractionAllowed->setGeometry(QRect(149, 147, 187, 35));
        label_car1tractionAllowed->setAlignment(Qt::AlignCenter);
        label_car3tractionAllowed = new QLabel(TractionPage);
        label_car3tractionAllowed->setObjectName(QString::fromUtf8("label_car3tractionAllowed"));
        label_car3tractionAllowed->setGeometry(QRect(544, 147, 210, 35));
        label_car3tractionAllowed->setAlignment(Qt::AlignCenter);
        label_tractionAllowed = new QLabel(TractionPage);
        label_tractionAllowed->setObjectName(QString::fromUtf8("label_tractionAllowed"));
        label_tractionAllowed->setGeometry(QRect(10, 147, 140, 35));
        label_car3safety1 = new QLabel(TractionPage);
        label_car3safety1->setObjectName(QString::fromUtf8("label_car3safety1"));
        label_car3safety1->setGeometry(QRect(700, 286, 53, 35));
        label_car3safety1->setAlignment(Qt::AlignCenter);
        label_car2safety2 = new QLabel(TractionPage);
        label_car2safety2->setObjectName(QString::fromUtf8("label_car2safety2"));
        label_car2safety2->setGeometry(QRect(387, 286, 52, 35));
        label_car2safety2->setAlignment(Qt::AlignCenter);
        label_car2safety3 = new QLabel(TractionPage);
        label_car2safety3->setObjectName(QString::fromUtf8("label_car2safety3"));
        label_car2safety3->setGeometry(QRect(439, 286, 52, 35));
        label_car2safety3->setAlignment(Qt::AlignCenter);
        label_car3safety4 = new QLabel(TractionPage);
        label_car3safety4->setObjectName(QString::fromUtf8("label_car3safety4"));
        label_car3safety4->setGeometry(QRect(544, 286, 52, 35));
        label_car3safety4->setAlignment(Qt::AlignCenter);
        label_car3safety3 = new QLabel(TractionPage);
        label_car3safety3->setObjectName(QString::fromUtf8("label_car3safety3"));
        label_car3safety3->setGeometry(QRect(596, 286, 52, 35));
        label_car3safety3->setAlignment(Qt::AlignCenter);
        label_car2safety4 = new QLabel(TractionPage);
        label_car2safety4->setObjectName(QString::fromUtf8("label_car2safety4"));
        label_car2safety4->setGeometry(QRect(491, 286, 53, 35));
        label_car2safety4->setAlignment(Qt::AlignCenter);
        label_car3safety2 = new QLabel(TractionPage);
        label_car3safety2->setObjectName(QString::fromUtf8("label_car3safety2"));
        label_car3safety2->setGeometry(QRect(648, 286, 52, 35));
        label_car3safety2->setAlignment(Qt::AlignCenter);
        label_car2safety1 = new QLabel(TractionPage);
        label_car2safety1->setObjectName(QString::fromUtf8("label_car2safety1"));
        label_car2safety1->setGeometry(QRect(335, 286, 52, 35));
        label_car2safety1->setStyleSheet(QString::fromUtf8(""));
        label_car2safety1->setAlignment(Qt::AlignCenter);
        label_car3inverterCurr1 = new QLabel(TractionPage);
        label_car3inverterCurr1->setObjectName(QString::fromUtf8("label_car3inverterCurr1"));
        label_car3inverterCurr1->setGeometry(QRect(701, 354, 53, 35));
        label_car3inverterCurr1->setAlignment(Qt::AlignCenter);
        label_car2inverterCurr3 = new QLabel(TractionPage);
        label_car2inverterCurr3->setObjectName(QString::fromUtf8("label_car2inverterCurr3"));
        label_car2inverterCurr3->setGeometry(QRect(440, 354, 52, 35));
        label_car2inverterCurr3->setAlignment(Qt::AlignCenter);
        label_car2inverterCurr1 = new QLabel(TractionPage);
        label_car2inverterCurr1->setObjectName(QString::fromUtf8("label_car2inverterCurr1"));
        label_car2inverterCurr1->setGeometry(QRect(336, 354, 52, 35));
        label_car2inverterCurr1->setStyleSheet(QString::fromUtf8(""));
        label_car2inverterCurr1->setAlignment(Qt::AlignCenter);
        label_car2inverterCurr4 = new QLabel(TractionPage);
        label_car2inverterCurr4->setObjectName(QString::fromUtf8("label_car2inverterCurr4"));
        label_car2inverterCurr4->setGeometry(QRect(492, 354, 53, 35));
        label_car2inverterCurr4->setAlignment(Qt::AlignCenter);
        label_car3inverterCurr2 = new QLabel(TractionPage);
        label_car3inverterCurr2->setObjectName(QString::fromUtf8("label_car3inverterCurr2"));
        label_car3inverterCurr2->setGeometry(QRect(649, 354, 52, 35));
        label_car3inverterCurr2->setAlignment(Qt::AlignCenter);
        label_car2inverterCurr2 = new QLabel(TractionPage);
        label_car2inverterCurr2->setObjectName(QString::fromUtf8("label_car2inverterCurr2"));
        label_car2inverterCurr2->setGeometry(QRect(388, 354, 52, 35));
        label_car2inverterCurr2->setAlignment(Qt::AlignCenter);
        label_car3inverterCurr3 = new QLabel(TractionPage);
        label_car3inverterCurr3->setObjectName(QString::fromUtf8("label_car3inverterCurr3"));
        label_car3inverterCurr3->setGeometry(QRect(597, 354, 52, 35));
        label_car3inverterCurr3->setAlignment(Qt::AlignCenter);
        label_car3inverterCurr4 = new QLabel(TractionPage);
        label_car3inverterCurr4->setObjectName(QString::fromUtf8("label_car3inverterCurr4"));
        label_car3inverterCurr4->setGeometry(QRect(545, 354, 52, 35));
        label_car3inverterCurr4->setAlignment(Qt::AlignCenter);
        label_car3EBEffect1 = new QLabel(TractionPage);
        label_car3EBEffect1->setObjectName(QString::fromUtf8("label_car3EBEffect1"));
        label_car3EBEffect1->setGeometry(QRect(701, 388, 53, 35));
        label_car3EBEffect1->setAlignment(Qt::AlignCenter);
        label_car2EBEffect2 = new QLabel(TractionPage);
        label_car2EBEffect2->setObjectName(QString::fromUtf8("label_car2EBEffect2"));
        label_car2EBEffect2->setGeometry(QRect(388, 388, 52, 35));
        label_car2EBEffect2->setAlignment(Qt::AlignCenter);
        label_car3EBEffect3 = new QLabel(TractionPage);
        label_car3EBEffect3->setObjectName(QString::fromUtf8("label_car3EBEffect3"));
        label_car3EBEffect3->setGeometry(QRect(597, 388, 52, 35));
        label_car3EBEffect3->setAlignment(Qt::AlignCenter);
        label_car3EBEffect2 = new QLabel(TractionPage);
        label_car3EBEffect2->setObjectName(QString::fromUtf8("label_car3EBEffect2"));
        label_car3EBEffect2->setGeometry(QRect(649, 388, 52, 35));
        label_car3EBEffect2->setAlignment(Qt::AlignCenter);
        label_car2EBEffect1 = new QLabel(TractionPage);
        label_car2EBEffect1->setObjectName(QString::fromUtf8("label_car2EBEffect1"));
        label_car2EBEffect1->setGeometry(QRect(336, 388, 52, 35));
        label_car2EBEffect1->setStyleSheet(QString::fromUtf8(""));
        label_car2EBEffect1->setAlignment(Qt::AlignCenter);
        label_car2EBEffect3 = new QLabel(TractionPage);
        label_car2EBEffect3->setObjectName(QString::fromUtf8("label_car2EBEffect3"));
        label_car2EBEffect3->setGeometry(QRect(440, 388, 52, 35));
        label_car2EBEffect3->setAlignment(Qt::AlignCenter);
        label_car3EBEffect4 = new QLabel(TractionPage);
        label_car3EBEffect4->setObjectName(QString::fromUtf8("label_car3EBEffect4"));
        label_car3EBEffect4->setGeometry(QRect(545, 388, 52, 35));
        label_car3EBEffect4->setAlignment(Qt::AlignCenter);
        label_car2EBEffect4 = new QLabel(TractionPage);
        label_car2EBEffect4->setObjectName(QString::fromUtf8("label_car2EBEffect4"));
        label_car2EBEffect4->setGeometry(QRect(492, 388, 53, 35));
        label_car2EBEffect4->setAlignment(Qt::AlignCenter);
        label_car2IsolateState4 = new QLabel(TractionPage);
        label_car2IsolateState4->setObjectName(QString::fromUtf8("label_car2IsolateState4"));
        label_car2IsolateState4->setGeometry(QRect(492, 490, 53, 35));
        label_car2IsolateState4->setAlignment(Qt::AlignCenter);
        label_car4IsolateState = new QLabel(TractionPage);
        label_car4IsolateState->setObjectName(QString::fromUtf8("label_car4IsolateState"));
        label_car4IsolateState->setGeometry(QRect(753, 490, 180, 35));
        label_car4IsolateState->setAlignment(Qt::AlignCenter);
        label_car3IsolateState2 = new QLabel(TractionPage);
        label_car3IsolateState2->setObjectName(QString::fromUtf8("label_car3IsolateState2"));
        label_car3IsolateState2->setGeometry(QRect(649, 490, 52, 35));
        label_car3IsolateState2->setAlignment(Qt::AlignCenter);
        label_isolateState = new QLabel(TractionPage);
        label_isolateState->setObjectName(QString::fromUtf8("label_isolateState"));
        label_isolateState->setGeometry(QRect(10, 490, 140, 35));
        label_car3IsolateState1 = new QLabel(TractionPage);
        label_car3IsolateState1->setObjectName(QString::fromUtf8("label_car3IsolateState1"));
        label_car3IsolateState1->setGeometry(QRect(701, 490, 53, 35));
        label_car3IsolateState1->setAlignment(Qt::AlignCenter);
        label_car1IsolateState = new QLabel(TractionPage);
        label_car1IsolateState->setObjectName(QString::fromUtf8("label_car1IsolateState"));
        label_car1IsolateState->setGeometry(QRect(149, 490, 187, 35));
        label_car1IsolateState->setAlignment(Qt::AlignCenter);
        label_car2IsolateState2 = new QLabel(TractionPage);
        label_car2IsolateState2->setObjectName(QString::fromUtf8("label_car2IsolateState2"));
        label_car2IsolateState2->setGeometry(QRect(388, 490, 52, 35));
        label_car2IsolateState2->setAlignment(Qt::AlignCenter);
        label_car2IsolateState3 = new QLabel(TractionPage);
        label_car2IsolateState3->setObjectName(QString::fromUtf8("label_car2IsolateState3"));
        label_car2IsolateState3->setGeometry(QRect(440, 490, 52, 35));
        label_car2IsolateState3->setAlignment(Qt::AlignCenter);
        label_car3IsolateState3 = new QLabel(TractionPage);
        label_car3IsolateState3->setObjectName(QString::fromUtf8("label_car3IsolateState3"));
        label_car3IsolateState3->setGeometry(QRect(597, 490, 52, 35));
        label_car3IsolateState3->setAlignment(Qt::AlignCenter);
        label_car2IsolateState1 = new QLabel(TractionPage);
        label_car2IsolateState1->setObjectName(QString::fromUtf8("label_car2IsolateState1"));
        label_car2IsolateState1->setGeometry(QRect(336, 490, 52, 35));
        label_car2IsolateState1->setStyleSheet(QString::fromUtf8(""));
        label_car2IsolateState1->setAlignment(Qt::AlignCenter);
        label_car3IsolateState4 = new QLabel(TractionPage);
        label_car3IsolateState4->setObjectName(QString::fromUtf8("label_car3IsolateState4"));
        label_car3IsolateState4->setGeometry(QRect(545, 490, 52, 35));
        label_car3IsolateState4->setAlignment(Qt::AlignCenter);

        retranslateUi(TractionPage);

        QMetaObject::connectSlotsByName(TractionPage);
    } // setupUi

    void retranslateUi(QWidget *TractionPage)
    {
        TractionPage->setWindowTitle(QApplication::translate("TractionPage", "Form", 0, QApplication::UnicodeUTF8));
        label_car1safety->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car4No->setText(QApplication::translate("TractionPage", "4", 0, QApplication::UnicodeUTF8));
        label_car2lineCurr1->setText(QString());
        label_car4AllBrakeRelease->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_HSCB->setText(QApplication::translate("TractionPage", "\351\253\230\351\200\237\346\226\255\350\267\257\345\231\250\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_car1EBEffect->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car3lineCurr2->setText(QString());
        label_car2HSCB->setText(QString());
        label_EBEffect->setText(QApplication::translate("TractionPage", "\345\256\236\351\231\205\347\224\265\345\210\266\345\212\250\345\212\233(N)", 0, QApplication::UnicodeUTF8));
        label_vehicleNo->setText(QApplication::translate("TractionPage", "\350\275\246\345\217\267", 0, QApplication::UnicodeUTF8));
        label_car3No->setText(QApplication::translate("TractionPage", "3", 0, QApplication::UnicodeUTF8));
        label_safetyBrake->setText(QApplication::translate("TractionPage", "\345\256\211\345\205\250\345\210\266\345\212\250", 0, QApplication::UnicodeUTF8));
        label_car4lineCurr->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car1inverterCurr->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car1No->setText(QApplication::translate("TractionPage", "1", 0, QApplication::UnicodeUTF8));
        label_car4EBState->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car1lineCurr->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_inverterCurr->setText(QApplication::translate("TractionPage", "\351\200\206\345\217\230\347\224\265\346\265\201(A)", 0, QApplication::UnicodeUTF8));
        label_car2No->setText(QApplication::translate("TractionPage", "2", 0, QApplication::UnicodeUTF8));
        label_car1HSCB->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_lineCurr->setText(QApplication::translate("TractionPage", "\346\257\215\347\272\277\347\224\265\346\265\201(A)", 0, QApplication::UnicodeUTF8));
        label_EBState->setText(QApplication::translate("TractionPage", "\347\224\265\345\210\266\345\212\250\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        btn_EmergencyBroadcast->setText(QApplication::translate("TractionPage", "\347\264\247\346\200\245\345\271\277\346\222\255", 0, QApplication::UnicodeUTF8));
        label_car4HSCB->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_allBrakeRelease->setText(QApplication::translate("TractionPage", "\346\211\200\346\234\211\345\210\266\345\212\250\347\274\223\350\247\243", 0, QApplication::UnicodeUTF8));
        label_car4inverterCurr->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car1EBState->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car4safety->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car4EBEffect->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car3HSCB->setText(QString());
        label_car1AllBrakeRelease->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car4Contactor->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car1Contactor->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_contactor->setText(QApplication::translate("TractionPage", "\344\270\273\346\216\245\350\247\246\345\231\250\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_car2Contactor1->setText(QString());
        label_car2Contactor2->setText(QString());
        label_car3Contactor1->setText(QString());
        label_car3Contactor2->setText(QString());
        label_car4chargeContactor->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_chargeContactor->setText(QApplication::translate("TractionPage", "\345\205\205\347\224\265\346\216\245\350\247\246\345\231\250\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_car3chargeContactor2->setText(QString());
        label_car2chargeContactor1->setText(QString());
        label_car1chargeContactor->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car2chargeContactor2->setText(QString());
        label_car3chargeContactor1->setText(QString());
        label_car3lineCurr1->setText(QString());
        label_car2lineCurr2->setText(QString());
        label_car2AllBR1->setText(QString());
        label_car2AllBR2->setText(QString());
        label_car2AllBR3->setText(QString());
        label_car2AllBR4->setText(QString());
        label_car3AllBR4->setText(QString());
        label_car3AllBR3->setText(QString());
        label_car3AllBR2->setText(QString());
        label_car3AllBR1->setText(QString());
        label_car3EBState1->setText(QString());
        label_car2EBState1->setText(QString());
        label_car2EBState3->setText(QString());
        label_car2EBState2->setText(QString());
        label_car2EBState4->setText(QString());
        label_car3EBState4->setText(QString());
        label_car3EBState2->setText(QString());
        label_car3EBState3->setText(QString());
        label_car4tractionAllowed->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car2tractionAllowed->setText(QString());
        label_car1tractionAllowed->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car3tractionAllowed->setText(QString());
        label_tractionAllowed->setText(QApplication::translate("TractionPage", "\347\211\265\345\274\225\345\205\201\350\256\270", 0, QApplication::UnicodeUTF8));
        label_car3safety1->setText(QString());
        label_car2safety2->setText(QString());
        label_car2safety3->setText(QString());
        label_car3safety4->setText(QString());
        label_car3safety3->setText(QString());
        label_car2safety4->setText(QString());
        label_car3safety2->setText(QString());
        label_car2safety1->setText(QString());
        label_car3inverterCurr1->setText(QString());
        label_car2inverterCurr3->setText(QString());
        label_car2inverterCurr1->setText(QString());
        label_car2inverterCurr4->setText(QString());
        label_car3inverterCurr2->setText(QString());
        label_car2inverterCurr2->setText(QString());
        label_car3inverterCurr3->setText(QString());
        label_car3inverterCurr4->setText(QString());
        label_car3EBEffect1->setText(QString());
        label_car2EBEffect2->setText(QString());
        label_car3EBEffect3->setText(QString());
        label_car3EBEffect2->setText(QString());
        label_car2EBEffect1->setText(QString());
        label_car2EBEffect3->setText(QString());
        label_car3EBEffect4->setText(QString());
        label_car2EBEffect4->setText(QString());
        label_car2IsolateState4->setText(QString());
        label_car4IsolateState->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car3IsolateState2->setText(QString());
        label_isolateState->setText(QApplication::translate("TractionPage", "\351\232\224\347\246\273\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_car3IsolateState1->setText(QString());
        label_car1IsolateState->setText(QApplication::translate("TractionPage", "--", 0, QApplication::UnicodeUTF8));
        label_car2IsolateState2->setText(QString());
        label_car2IsolateState3->setText(QString());
        label_car3IsolateState3->setText(QString());
        label_car2IsolateState1->setText(QString());
        label_car3IsolateState4->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class TractionPage: public Ui_TractionPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TRACTIONPAGE_H
