/********************************************************************************
** Form generated from reading UI file 'versioninfopage.ui'
**
** Created: Thu May 24 10:33:18 2018
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VERSIONINFOPAGE_H
#define UI_VERSIONINFOPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VersionInfoPage
{
public:
    QLabel *label_HVAC;
    QLabel *label_HMI1;
    QLabel *label_car1Door1_1;
    QLabel *label_HMI4;
    QLabel *label_AX1;
    QLabel *label_DI4;
    QLabel *label_SIV2;
    QLabel *label_AX2;
    QLabel *label_SIV4;
    QLabel *label_HMI2;
    QLabel *label_AX4;
    QLabel *label_AX3;
    QLabel *label_car4Door1_1;
    QLabel *label_DO1;
    QLabel *label_HVAC3;
    QLabel *label_GW3;
    QLabel *label_FAU2;
    QLabel *label_DO2;
    QLabel *label_PIS;
    QLabel *label_DO3;
    QLabel *label_HMI;
    QLabel *label_GW1;
    QLabel *label_ATC;
    QLabel *label_BCU1;
    QLabel *label_PIS4;
    QLabel *label_DI2;
    QLabel *label_PIS3;
    QLabel *label_BCU;
    QLabel *label_SIV;
    QLabel *label_car3Door1_1;
    QLabel *label_DI1;
    QLabel *label_BCU2;
    QLabel *label_AX;
    QLabel *label_DO;
    QLabel *label_FAU4;
    QLabel *label_HMI3;
    QLabel *label_DI3;
    QLabel *label_DI;
    QLabel *label_CCU2;
    QLabel *label_PIS2;
    QLabel *label_CCU1;
    QLabel *label_HVAC1;
    QLabel *label_FAU3;
    QLabel *label_FAU;
    QLabel *label_car2Door1_1;
    QLabel *label_SIV1;
    QLabel *label_DO4;
    QLabel *label_Door2;
    QLabel *label_GW2;
    QLabel *label_DCU;
    QLabel *label_SIV3;
    QLabel *label_HVAC2;
    QPushButton *btn_back;
    QLabel *label_GW;
    QLabel *label_GW4;
    QLabel *label_HVAC4;
    QLabel *label_CCU;
    QLabel *label_FAU1;
    QLabel *label_PIS1;
    QLabel *label_ERM1;
    QLabel *label_ERM;
    QLabel *label_ERM2;
    QLabel *label_car1Door1_2;
    QLabel *label_car1Door1_3;
    QLabel *label_car1Door1_4;
    QLabel *label_car2Door1_2;
    QLabel *label_car2Door1_3;
    QLabel *label_car2Door1_4;
    QLabel *label_car3Door1_2;
    QLabel *label_car3Door1_3;
    QLabel *label_car3Door1_4;
    QLabel *label_car4Door1_2;
    QLabel *label_car4Door1_3;
    QLabel *label_car4Door1_4;
    QLabel *label_car4Door2_4;
    QLabel *label_car2Door2_1;
    QLabel *label_car3Door2_2;
    QLabel *label_car1Door2_2;
    QLabel *label_car3Door2_3;
    QLabel *label_car4Door2_3;
    QLabel *label_car4Door2_1;
    QLabel *label_car2Door2_2;
    QLabel *label_car4Door2_2;
    QLabel *label_car1Door2_3;
    QLabel *label_car1Door2_4;
    QLabel *label_car2Door2_4;
    QLabel *label_car2Door2_3;
    QLabel *label_car3Door2_4;
    QLabel *label_car1Door2_1;
    QLabel *label_car3Door2_1;
    QLabel *label_BCG1;
    QLabel *label_PDS2;
    QLabel *label_BMS4;
    QLabel *label_PDS4;
    QLabel *label_BCG4;
    QLabel *label_BCG3;
    QLabel *label_PDS;
    QLabel *label_BMS;
    QLabel *label_BMS3;
    QLabel *label_BMS1;
    QLabel *label_BCG2;
    QLabel *label_BCG;
    QLabel *label_PDS1;
    QLabel *label_BMS2;
    QLabel *label_PDS3;
    QLabel *label_car2DCU2;
    QLabel *label_car2DCU4;
    QLabel *label_car1DCU;
    QLabel *label_car4DCU;
    QLabel *label_car3DCU4;
    QLabel *label_car2DCU1;
    QLabel *label_car3DCU1;
    QLabel *label_car3DCU3;
    QLabel *label_car2DCU3;
    QLabel *label_car3DCU2;
    QLabel *label_car2DCUGW;
    QLabel *label_car3DCUGW;
    QLabel *label_SIVGW4;
    QLabel *label_SIVGW1;

    void setupUi(QWidget *VersionInfoPage)
    {
        if (VersionInfoPage->objectName().isEmpty())
            VersionInfoPage->setObjectName(QString::fromUtf8("VersionInfoPage"));
        VersionInfoPage->resize(1024, 708);
        VersionInfoPage->setStyleSheet(QString::fromUtf8("QLabel\n"
"{\n"
"	color: white;\n"
"	border: 2px groove, gray;\n"
"    border-color: gray;\n"
"	font: 20px, \"SimHei\";	\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"	background-color: black;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"	font: 20px, \"SimHei\";\n"
"    color: black;\n"
"	background-color: rgb(250, 250, 250);\n"
"	border-radius: 5px;\n"
"}"));
        label_HVAC = new QLabel(VersionInfoPage);
        label_HVAC->setObjectName(QString::fromUtf8("label_HVAC"));
        label_HVAC->setGeometry(QRect(33, 309, 130, 30));
        label_HMI1 = new QLabel(VersionInfoPage);
        label_HMI1->setObjectName(QString::fromUtf8("label_HMI1"));
        label_HMI1->setGeometry(QRect(162, 518, 190, 30));
        label_car1Door1_1 = new QLabel(VersionInfoPage);
        label_car1Door1_1->setObjectName(QString::fromUtf8("label_car1Door1_1"));
        label_car1Door1_1->setGeometry(QRect(162, 339, 95, 30));
        label_car1Door1_1->setStyleSheet(QString::fromUtf8(""));
        label_HMI4 = new QLabel(VersionInfoPage);
        label_HMI4->setObjectName(QString::fromUtf8("label_HMI4"));
        label_HMI4->setGeometry(QRect(769, 518, 180, 30));
        label_AX1 = new QLabel(VersionInfoPage);
        label_AX1->setObjectName(QString::fromUtf8("label_AX1"));
        label_AX1->setGeometry(QRect(162, 170, 190, 31));
        label_DI4 = new QLabel(VersionInfoPage);
        label_DI4->setObjectName(QString::fromUtf8("label_DI4"));
        label_DI4->setGeometry(QRect(769, 112, 180, 30));
        label_SIV2 = new QLabel(VersionInfoPage);
        label_SIV2->setObjectName(QString::fromUtf8("label_SIV2"));
        label_SIV2->setGeometry(QRect(351, 200, 210, 41));
        label_AX2 = new QLabel(VersionInfoPage);
        label_AX2->setObjectName(QString::fromUtf8("label_AX2"));
        label_AX2->setGeometry(QRect(351, 170, 210, 31));
        label_SIV4 = new QLabel(VersionInfoPage);
        label_SIV4->setObjectName(QString::fromUtf8("label_SIV4"));
        label_SIV4->setGeometry(QRect(769, 200, 180, 20));
        label_SIV4->setStyleSheet(QString::fromUtf8(""));
        label_HMI2 = new QLabel(VersionInfoPage);
        label_HMI2->setObjectName(QString::fromUtf8("label_HMI2"));
        label_HMI2->setGeometry(QRect(351, 518, 210, 30));
        label_AX4 = new QLabel(VersionInfoPage);
        label_AX4->setObjectName(QString::fromUtf8("label_AX4"));
        label_AX4->setGeometry(QRect(769, 170, 180, 31));
        label_AX3 = new QLabel(VersionInfoPage);
        label_AX3->setObjectName(QString::fromUtf8("label_AX3"));
        label_AX3->setGeometry(QRect(560, 170, 210, 31));
        label_car4Door1_1 = new QLabel(VersionInfoPage);
        label_car4Door1_1->setObjectName(QString::fromUtf8("label_car4Door1_1"));
        label_car4Door1_1->setGeometry(QRect(769, 339, 90, 30));
        label_car4Door1_1->setStyleSheet(QString::fromUtf8(""));
        label_DO1 = new QLabel(VersionInfoPage);
        label_DO1->setObjectName(QString::fromUtf8("label_DO1"));
        label_DO1->setGeometry(QRect(162, 141, 190, 30));
        label_HVAC3 = new QLabel(VersionInfoPage);
        label_HVAC3->setObjectName(QString::fromUtf8("label_HVAC3"));
        label_HVAC3->setGeometry(QRect(560, 309, 210, 30));
        label_GW3 = new QLabel(VersionInfoPage);
        label_GW3->setObjectName(QString::fromUtf8("label_GW3"));
        label_GW3->setGeometry(QRect(560, 83, 210, 30));
        label_FAU2 = new QLabel(VersionInfoPage);
        label_FAU2->setObjectName(QString::fromUtf8("label_FAU2"));
        label_FAU2->setGeometry(QRect(351, 488, 210, 30));
        label_DO2 = new QLabel(VersionInfoPage);
        label_DO2->setObjectName(QString::fromUtf8("label_DO2"));
        label_DO2->setGeometry(QRect(351, 141, 210, 30));
        label_PIS = new QLabel(VersionInfoPage);
        label_PIS->setObjectName(QString::fromUtf8("label_PIS"));
        label_PIS->setGeometry(QRect(33, 458, 130, 30));
        label_DO3 = new QLabel(VersionInfoPage);
        label_DO3->setObjectName(QString::fromUtf8("label_DO3"));
        label_DO3->setGeometry(QRect(560, 141, 210, 30));
        label_HMI = new QLabel(VersionInfoPage);
        label_HMI->setObjectName(QString::fromUtf8("label_HMI"));
        label_HMI->setGeometry(QRect(33, 518, 130, 30));
        label_GW1 = new QLabel(VersionInfoPage);
        label_GW1->setObjectName(QString::fromUtf8("label_GW1"));
        label_GW1->setGeometry(QRect(162, 83, 190, 30));
        label_ATC = new QLabel(VersionInfoPage);
        label_ATC->setObjectName(QString::fromUtf8("label_ATC"));
        label_ATC->setGeometry(QRect(33, 339, 130, 60));
        label_BCU1 = new QLabel(VersionInfoPage);
        label_BCU1->setObjectName(QString::fromUtf8("label_BCU1"));
        label_BCU1->setGeometry(QRect(162, 240, 399, 30));
        label_BCU1->setStyleSheet(QString::fromUtf8("	font: 15px, \"SimHei\";	"));
        label_PIS4 = new QLabel(VersionInfoPage);
        label_PIS4->setObjectName(QString::fromUtf8("label_PIS4"));
        label_PIS4->setGeometry(QRect(769, 458, 180, 30));
        label_DI2 = new QLabel(VersionInfoPage);
        label_DI2->setObjectName(QString::fromUtf8("label_DI2"));
        label_DI2->setGeometry(QRect(351, 112, 210, 30));
        label_PIS3 = new QLabel(VersionInfoPage);
        label_PIS3->setObjectName(QString::fromUtf8("label_PIS3"));
        label_PIS3->setGeometry(QRect(560, 458, 210, 30));
        label_BCU = new QLabel(VersionInfoPage);
        label_BCU->setObjectName(QString::fromUtf8("label_BCU"));
        label_BCU->setGeometry(QRect(33, 240, 130, 30));
        label_SIV = new QLabel(VersionInfoPage);
        label_SIV->setObjectName(QString::fromUtf8("label_SIV"));
        label_SIV->setGeometry(QRect(33, 200, 130, 41));
        label_car3Door1_1 = new QLabel(VersionInfoPage);
        label_car3Door1_1->setObjectName(QString::fromUtf8("label_car3Door1_1"));
        label_car3Door1_1->setGeometry(QRect(560, 339, 105, 30));
        label_car3Door1_1->setStyleSheet(QString::fromUtf8(""));
        label_DI1 = new QLabel(VersionInfoPage);
        label_DI1->setObjectName(QString::fromUtf8("label_DI1"));
        label_DI1->setGeometry(QRect(162, 112, 190, 30));
        label_BCU2 = new QLabel(VersionInfoPage);
        label_BCU2->setObjectName(QString::fromUtf8("label_BCU2"));
        label_BCU2->setGeometry(QRect(560, 240, 389, 30));
        label_BCU2->setStyleSheet(QString::fromUtf8("	font: 15px, \"SimHei\";	"));
        label_AX = new QLabel(VersionInfoPage);
        label_AX->setObjectName(QString::fromUtf8("label_AX"));
        label_AX->setGeometry(QRect(33, 170, 130, 31));
        label_DO = new QLabel(VersionInfoPage);
        label_DO->setObjectName(QString::fromUtf8("label_DO"));
        label_DO->setGeometry(QRect(33, 141, 130, 30));
        label_FAU4 = new QLabel(VersionInfoPage);
        label_FAU4->setObjectName(QString::fromUtf8("label_FAU4"));
        label_FAU4->setGeometry(QRect(769, 488, 180, 30));
        label_HMI3 = new QLabel(VersionInfoPage);
        label_HMI3->setObjectName(QString::fromUtf8("label_HMI3"));
        label_HMI3->setGeometry(QRect(560, 518, 210, 30));
        label_DI3 = new QLabel(VersionInfoPage);
        label_DI3->setObjectName(QString::fromUtf8("label_DI3"));
        label_DI3->setGeometry(QRect(560, 112, 210, 30));
        label_DI = new QLabel(VersionInfoPage);
        label_DI->setObjectName(QString::fromUtf8("label_DI"));
        label_DI->setGeometry(QRect(33, 112, 130, 30));
        label_CCU2 = new QLabel(VersionInfoPage);
        label_CCU2->setObjectName(QString::fromUtf8("label_CCU2"));
        label_CCU2->setGeometry(QRect(560, 26, 389, 30));
        label_CCU2->setStyleSheet(QString::fromUtf8("font: 15px, \"SimHei\";	"));
        label_PIS2 = new QLabel(VersionInfoPage);
        label_PIS2->setObjectName(QString::fromUtf8("label_PIS2"));
        label_PIS2->setGeometry(QRect(351, 458, 210, 30));
        label_CCU1 = new QLabel(VersionInfoPage);
        label_CCU1->setObjectName(QString::fromUtf8("label_CCU1"));
        label_CCU1->setGeometry(QRect(162, 26, 399, 30));
        label_CCU1->setStyleSheet(QString::fromUtf8("font: 15px, \"SimHei\";	"));
        label_HVAC1 = new QLabel(VersionInfoPage);
        label_HVAC1->setObjectName(QString::fromUtf8("label_HVAC1"));
        label_HVAC1->setGeometry(QRect(162, 309, 190, 30));
        label_FAU3 = new QLabel(VersionInfoPage);
        label_FAU3->setObjectName(QString::fromUtf8("label_FAU3"));
        label_FAU3->setGeometry(QRect(560, 488, 210, 30));
        label_FAU = new QLabel(VersionInfoPage);
        label_FAU->setObjectName(QString::fromUtf8("label_FAU"));
        label_FAU->setGeometry(QRect(33, 488, 130, 30));
        label_car2Door1_1 = new QLabel(VersionInfoPage);
        label_car2Door1_1->setObjectName(QString::fromUtf8("label_car2Door1_1"));
        label_car2Door1_1->setGeometry(QRect(351, 339, 105, 30));
        label_car2Door1_1->setStyleSheet(QString::fromUtf8(""));
        label_SIV1 = new QLabel(VersionInfoPage);
        label_SIV1->setObjectName(QString::fromUtf8("label_SIV1"));
        label_SIV1->setGeometry(QRect(162, 200, 190, 20));
        label_SIV1->setStyleSheet(QString::fromUtf8(""));
        label_DO4 = new QLabel(VersionInfoPage);
        label_DO4->setObjectName(QString::fromUtf8("label_DO4"));
        label_DO4->setGeometry(QRect(769, 141, 180, 30));
        label_Door2 = new QLabel(VersionInfoPage);
        label_Door2->setObjectName(QString::fromUtf8("label_Door2"));
        label_Door2->setGeometry(QRect(33, 398, 130, 60));
        label_GW2 = new QLabel(VersionInfoPage);
        label_GW2->setObjectName(QString::fromUtf8("label_GW2"));
        label_GW2->setGeometry(QRect(351, 83, 210, 30));
        label_DCU = new QLabel(VersionInfoPage);
        label_DCU->setObjectName(QString::fromUtf8("label_DCU"));
        label_DCU->setGeometry(QRect(33, 270, 130, 39));
        label_SIV3 = new QLabel(VersionInfoPage);
        label_SIV3->setObjectName(QString::fromUtf8("label_SIV3"));
        label_SIV3->setGeometry(QRect(560, 200, 210, 41));
        label_HVAC2 = new QLabel(VersionInfoPage);
        label_HVAC2->setObjectName(QString::fromUtf8("label_HVAC2"));
        label_HVAC2->setGeometry(QRect(351, 309, 210, 30));
        btn_back = new QPushButton(VersionInfoPage);
        btn_back->setObjectName(QString::fromUtf8("btn_back"));
        btn_back->setGeometry(QRect(910, 660, 98, 40));
        label_GW = new QLabel(VersionInfoPage);
        label_GW->setObjectName(QString::fromUtf8("label_GW"));
        label_GW->setGeometry(QRect(33, 83, 130, 30));
        label_GW4 = new QLabel(VersionInfoPage);
        label_GW4->setObjectName(QString::fromUtf8("label_GW4"));
        label_GW4->setGeometry(QRect(769, 83, 180, 30));
        label_HVAC4 = new QLabel(VersionInfoPage);
        label_HVAC4->setObjectName(QString::fromUtf8("label_HVAC4"));
        label_HVAC4->setGeometry(QRect(769, 309, 180, 30));
        label_CCU = new QLabel(VersionInfoPage);
        label_CCU->setObjectName(QString::fromUtf8("label_CCU"));
        label_CCU->setGeometry(QRect(33, 26, 130, 30));
        label_FAU1 = new QLabel(VersionInfoPage);
        label_FAU1->setObjectName(QString::fromUtf8("label_FAU1"));
        label_FAU1->setGeometry(QRect(162, 488, 190, 30));
        label_PIS1 = new QLabel(VersionInfoPage);
        label_PIS1->setObjectName(QString::fromUtf8("label_PIS1"));
        label_PIS1->setGeometry(QRect(162, 458, 190, 30));
        label_ERM1 = new QLabel(VersionInfoPage);
        label_ERM1->setObjectName(QString::fromUtf8("label_ERM1"));
        label_ERM1->setGeometry(QRect(162, 55, 399, 30));
        label_ERM1->setStyleSheet(QString::fromUtf8("	font: 17px, \"SimHei\";	"));
        label_ERM = new QLabel(VersionInfoPage);
        label_ERM->setObjectName(QString::fromUtf8("label_ERM"));
        label_ERM->setGeometry(QRect(33, 55, 130, 30));
        label_ERM2 = new QLabel(VersionInfoPage);
        label_ERM2->setObjectName(QString::fromUtf8("label_ERM2"));
        label_ERM2->setGeometry(QRect(560, 55, 389, 30));
        label_ERM2->setStyleSheet(QString::fromUtf8("font: 17px, \"SimHei\";	"));
        label_car1Door1_2 = new QLabel(VersionInfoPage);
        label_car1Door1_2->setObjectName(QString::fromUtf8("label_car1Door1_2"));
        label_car1Door1_2->setGeometry(QRect(257, 339, 95, 30));
        label_car1Door1_2->setStyleSheet(QString::fromUtf8(""));
        label_car1Door1_3 = new QLabel(VersionInfoPage);
        label_car1Door1_3->setObjectName(QString::fromUtf8("label_car1Door1_3"));
        label_car1Door1_3->setGeometry(QRect(162, 369, 95, 30));
        label_car1Door1_3->setStyleSheet(QString::fromUtf8(""));
        label_car1Door1_4 = new QLabel(VersionInfoPage);
        label_car1Door1_4->setObjectName(QString::fromUtf8("label_car1Door1_4"));
        label_car1Door1_4->setGeometry(QRect(257, 369, 95, 30));
        label_car1Door1_4->setStyleSheet(QString::fromUtf8(""));
        label_car2Door1_2 = new QLabel(VersionInfoPage);
        label_car2Door1_2->setObjectName(QString::fromUtf8("label_car2Door1_2"));
        label_car2Door1_2->setGeometry(QRect(456, 339, 104, 30));
        label_car2Door1_2->setStyleSheet(QString::fromUtf8(""));
        label_car2Door1_3 = new QLabel(VersionInfoPage);
        label_car2Door1_3->setObjectName(QString::fromUtf8("label_car2Door1_3"));
        label_car2Door1_3->setGeometry(QRect(351, 369, 105, 30));
        label_car2Door1_3->setStyleSheet(QString::fromUtf8(""));
        label_car2Door1_4 = new QLabel(VersionInfoPage);
        label_car2Door1_4->setObjectName(QString::fromUtf8("label_car2Door1_4"));
        label_car2Door1_4->setGeometry(QRect(456, 369, 104, 30));
        label_car2Door1_4->setStyleSheet(QString::fromUtf8(""));
        label_car3Door1_2 = new QLabel(VersionInfoPage);
        label_car3Door1_2->setObjectName(QString::fromUtf8("label_car3Door1_2"));
        label_car3Door1_2->setGeometry(QRect(665, 339, 104, 30));
        label_car3Door1_2->setStyleSheet(QString::fromUtf8(""));
        label_car3Door1_3 = new QLabel(VersionInfoPage);
        label_car3Door1_3->setObjectName(QString::fromUtf8("label_car3Door1_3"));
        label_car3Door1_3->setGeometry(QRect(560, 369, 105, 30));
        label_car3Door1_3->setStyleSheet(QString::fromUtf8(""));
        label_car3Door1_4 = new QLabel(VersionInfoPage);
        label_car3Door1_4->setObjectName(QString::fromUtf8("label_car3Door1_4"));
        label_car3Door1_4->setGeometry(QRect(665, 369, 104, 30));
        label_car3Door1_4->setStyleSheet(QString::fromUtf8(""));
        label_car4Door1_2 = new QLabel(VersionInfoPage);
        label_car4Door1_2->setObjectName(QString::fromUtf8("label_car4Door1_2"));
        label_car4Door1_2->setGeometry(QRect(858, 339, 91, 30));
        label_car4Door1_2->setStyleSheet(QString::fromUtf8(""));
        label_car4Door1_3 = new QLabel(VersionInfoPage);
        label_car4Door1_3->setObjectName(QString::fromUtf8("label_car4Door1_3"));
        label_car4Door1_3->setGeometry(QRect(769, 369, 90, 30));
        label_car4Door1_3->setStyleSheet(QString::fromUtf8(""));
        label_car4Door1_4 = new QLabel(VersionInfoPage);
        label_car4Door1_4->setObjectName(QString::fromUtf8("label_car4Door1_4"));
        label_car4Door1_4->setGeometry(QRect(858, 369, 91, 30));
        label_car4Door1_4->setStyleSheet(QString::fromUtf8(""));
        label_car4Door2_4 = new QLabel(VersionInfoPage);
        label_car4Door2_4->setObjectName(QString::fromUtf8("label_car4Door2_4"));
        label_car4Door2_4->setGeometry(QRect(858, 428, 91, 30));
        label_car4Door2_4->setStyleSheet(QString::fromUtf8(""));
        label_car2Door2_1 = new QLabel(VersionInfoPage);
        label_car2Door2_1->setObjectName(QString::fromUtf8("label_car2Door2_1"));
        label_car2Door2_1->setGeometry(QRect(351, 398, 105, 30));
        label_car2Door2_1->setStyleSheet(QString::fromUtf8(""));
        label_car3Door2_2 = new QLabel(VersionInfoPage);
        label_car3Door2_2->setObjectName(QString::fromUtf8("label_car3Door2_2"));
        label_car3Door2_2->setGeometry(QRect(665, 398, 104, 30));
        label_car3Door2_2->setStyleSheet(QString::fromUtf8(""));
        label_car1Door2_2 = new QLabel(VersionInfoPage);
        label_car1Door2_2->setObjectName(QString::fromUtf8("label_car1Door2_2"));
        label_car1Door2_2->setGeometry(QRect(257, 398, 95, 30));
        label_car1Door2_2->setStyleSheet(QString::fromUtf8(""));
        label_car3Door2_3 = new QLabel(VersionInfoPage);
        label_car3Door2_3->setObjectName(QString::fromUtf8("label_car3Door2_3"));
        label_car3Door2_3->setGeometry(QRect(560, 428, 105, 30));
        label_car3Door2_3->setStyleSheet(QString::fromUtf8(""));
        label_car4Door2_3 = new QLabel(VersionInfoPage);
        label_car4Door2_3->setObjectName(QString::fromUtf8("label_car4Door2_3"));
        label_car4Door2_3->setGeometry(QRect(769, 428, 90, 30));
        label_car4Door2_3->setStyleSheet(QString::fromUtf8(""));
        label_car4Door2_1 = new QLabel(VersionInfoPage);
        label_car4Door2_1->setObjectName(QString::fromUtf8("label_car4Door2_1"));
        label_car4Door2_1->setGeometry(QRect(769, 398, 90, 30));
        label_car4Door2_1->setStyleSheet(QString::fromUtf8(""));
        label_car2Door2_2 = new QLabel(VersionInfoPage);
        label_car2Door2_2->setObjectName(QString::fromUtf8("label_car2Door2_2"));
        label_car2Door2_2->setGeometry(QRect(456, 398, 104, 30));
        label_car2Door2_2->setStyleSheet(QString::fromUtf8(""));
        label_car4Door2_2 = new QLabel(VersionInfoPage);
        label_car4Door2_2->setObjectName(QString::fromUtf8("label_car4Door2_2"));
        label_car4Door2_2->setGeometry(QRect(858, 398, 91, 30));
        label_car4Door2_2->setStyleSheet(QString::fromUtf8(""));
        label_car1Door2_3 = new QLabel(VersionInfoPage);
        label_car1Door2_3->setObjectName(QString::fromUtf8("label_car1Door2_3"));
        label_car1Door2_3->setGeometry(QRect(162, 428, 95, 30));
        label_car1Door2_3->setStyleSheet(QString::fromUtf8(""));
        label_car1Door2_4 = new QLabel(VersionInfoPage);
        label_car1Door2_4->setObjectName(QString::fromUtf8("label_car1Door2_4"));
        label_car1Door2_4->setGeometry(QRect(257, 428, 95, 30));
        label_car1Door2_4->setStyleSheet(QString::fromUtf8(""));
        label_car2Door2_4 = new QLabel(VersionInfoPage);
        label_car2Door2_4->setObjectName(QString::fromUtf8("label_car2Door2_4"));
        label_car2Door2_4->setGeometry(QRect(456, 428, 104, 30));
        label_car2Door2_4->setStyleSheet(QString::fromUtf8(""));
        label_car2Door2_3 = new QLabel(VersionInfoPage);
        label_car2Door2_3->setObjectName(QString::fromUtf8("label_car2Door2_3"));
        label_car2Door2_3->setGeometry(QRect(351, 428, 105, 30));
        label_car2Door2_3->setStyleSheet(QString::fromUtf8(""));
        label_car3Door2_4 = new QLabel(VersionInfoPage);
        label_car3Door2_4->setObjectName(QString::fromUtf8("label_car3Door2_4"));
        label_car3Door2_4->setGeometry(QRect(665, 428, 104, 30));
        label_car3Door2_4->setStyleSheet(QString::fromUtf8(""));
        label_car1Door2_1 = new QLabel(VersionInfoPage);
        label_car1Door2_1->setObjectName(QString::fromUtf8("label_car1Door2_1"));
        label_car1Door2_1->setGeometry(QRect(162, 398, 95, 30));
        label_car1Door2_1->setStyleSheet(QString::fromUtf8(""));
        label_car3Door2_1 = new QLabel(VersionInfoPage);
        label_car3Door2_1->setObjectName(QString::fromUtf8("label_car3Door2_1"));
        label_car3Door2_1->setGeometry(QRect(560, 398, 105, 30));
        label_car3Door2_1->setStyleSheet(QString::fromUtf8(""));
        label_BCG1 = new QLabel(VersionInfoPage);
        label_BCG1->setObjectName(QString::fromUtf8("label_BCG1"));
        label_BCG1->setGeometry(QRect(162, 547, 190, 30));
        label_PDS2 = new QLabel(VersionInfoPage);
        label_PDS2->setObjectName(QString::fromUtf8("label_PDS2"));
        label_PDS2->setGeometry(QRect(351, 576, 210, 30));
        label_BMS4 = new QLabel(VersionInfoPage);
        label_BMS4->setObjectName(QString::fromUtf8("label_BMS4"));
        label_BMS4->setGeometry(QRect(769, 605, 180, 30));
        label_PDS4 = new QLabel(VersionInfoPage);
        label_PDS4->setObjectName(QString::fromUtf8("label_PDS4"));
        label_PDS4->setGeometry(QRect(769, 576, 180, 30));
        label_BCG4 = new QLabel(VersionInfoPage);
        label_BCG4->setObjectName(QString::fromUtf8("label_BCG4"));
        label_BCG4->setGeometry(QRect(769, 547, 180, 30));
        label_BCG3 = new QLabel(VersionInfoPage);
        label_BCG3->setObjectName(QString::fromUtf8("label_BCG3"));
        label_BCG3->setGeometry(QRect(560, 547, 210, 30));
        label_PDS = new QLabel(VersionInfoPage);
        label_PDS->setObjectName(QString::fromUtf8("label_PDS"));
        label_PDS->setGeometry(QRect(33, 576, 130, 30));
        label_BMS = new QLabel(VersionInfoPage);
        label_BMS->setObjectName(QString::fromUtf8("label_BMS"));
        label_BMS->setGeometry(QRect(33, 605, 130, 30));
        label_BMS3 = new QLabel(VersionInfoPage);
        label_BMS3->setObjectName(QString::fromUtf8("label_BMS3"));
        label_BMS3->setGeometry(QRect(560, 605, 210, 30));
        label_BMS1 = new QLabel(VersionInfoPage);
        label_BMS1->setObjectName(QString::fromUtf8("label_BMS1"));
        label_BMS1->setGeometry(QRect(162, 605, 190, 30));
        label_BCG2 = new QLabel(VersionInfoPage);
        label_BCG2->setObjectName(QString::fromUtf8("label_BCG2"));
        label_BCG2->setGeometry(QRect(351, 547, 210, 30));
        label_BCG = new QLabel(VersionInfoPage);
        label_BCG->setObjectName(QString::fromUtf8("label_BCG"));
        label_BCG->setGeometry(QRect(33, 547, 130, 30));
        label_PDS1 = new QLabel(VersionInfoPage);
        label_PDS1->setObjectName(QString::fromUtf8("label_PDS1"));
        label_PDS1->setGeometry(QRect(162, 576, 190, 30));
        label_BMS2 = new QLabel(VersionInfoPage);
        label_BMS2->setObjectName(QString::fromUtf8("label_BMS2"));
        label_BMS2->setGeometry(QRect(351, 605, 210, 30));
        label_PDS3 = new QLabel(VersionInfoPage);
        label_PDS3->setObjectName(QString::fromUtf8("label_PDS3"));
        label_PDS3->setGeometry(QRect(560, 576, 210, 30));
        label_car2DCU2 = new QLabel(VersionInfoPage);
        label_car2DCU2->setObjectName(QString::fromUtf8("label_car2DCU2"));
        label_car2DCU2->setGeometry(QRect(403, 290, 53, 20));
        label_car2DCU2->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car2DCU4 = new QLabel(VersionInfoPage);
        label_car2DCU4->setObjectName(QString::fromUtf8("label_car2DCU4"));
        label_car2DCU4->setGeometry(QRect(509, 290, 52, 20));
        label_car2DCU4->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car1DCU = new QLabel(VersionInfoPage);
        label_car1DCU->setObjectName(QString::fromUtf8("label_car1DCU"));
        label_car1DCU->setGeometry(QRect(162, 270, 190, 39));
        label_car4DCU = new QLabel(VersionInfoPage);
        label_car4DCU->setObjectName(QString::fromUtf8("label_car4DCU"));
        label_car4DCU->setGeometry(QRect(769, 270, 180, 39));
        label_car3DCU4 = new QLabel(VersionInfoPage);
        label_car3DCU4->setObjectName(QString::fromUtf8("label_car3DCU4"));
        label_car3DCU4->setGeometry(QRect(717, 290, 52, 20));
        label_car3DCU4->setStyleSheet(QString::fromUtf8("font: 12px, \"SimHei\";	"));
        label_car2DCU1 = new QLabel(VersionInfoPage);
        label_car2DCU1->setObjectName(QString::fromUtf8("label_car2DCU1"));
        label_car2DCU1->setGeometry(QRect(351, 290, 52, 20));
        label_car2DCU1->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car3DCU1 = new QLabel(VersionInfoPage);
        label_car3DCU1->setObjectName(QString::fromUtf8("label_car3DCU1"));
        label_car3DCU1->setGeometry(QRect(560, 290, 52, 20));
        label_car3DCU1->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car3DCU3 = new QLabel(VersionInfoPage);
        label_car3DCU3->setObjectName(QString::fromUtf8("label_car3DCU3"));
        label_car3DCU3->setGeometry(QRect(665, 290, 52, 20));
        label_car3DCU3->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car2DCU3 = new QLabel(VersionInfoPage);
        label_car2DCU3->setObjectName(QString::fromUtf8("label_car2DCU3"));
        label_car2DCU3->setGeometry(QRect(456, 290, 53, 20));
        label_car2DCU3->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car3DCU2 = new QLabel(VersionInfoPage);
        label_car3DCU2->setObjectName(QString::fromUtf8("label_car3DCU2"));
        label_car3DCU2->setGeometry(QRect(612, 290, 53, 20));
        label_car3DCU2->setStyleSheet(QString::fromUtf8("	font: 12px, \"SimHei\";	"));
        label_car2DCUGW = new QLabel(VersionInfoPage);
        label_car2DCUGW->setObjectName(QString::fromUtf8("label_car2DCUGW"));
        label_car2DCUGW->setGeometry(QRect(351, 270, 210, 20));
        label_car2DCUGW->setStyleSheet(QString::fromUtf8("	font: 15px, \"SimHei\";	"));
        label_car3DCUGW = new QLabel(VersionInfoPage);
        label_car3DCUGW->setObjectName(QString::fromUtf8("label_car3DCUGW"));
        label_car3DCUGW->setGeometry(QRect(560, 270, 210, 20));
        label_car3DCUGW->setStyleSheet(QString::fromUtf8("	font: 15px, \"SimHei\";	"));
        label_SIVGW4 = new QLabel(VersionInfoPage);
        label_SIVGW4->setObjectName(QString::fromUtf8("label_SIVGW4"));
        label_SIVGW4->setGeometry(QRect(769, 220, 180, 20));
        label_SIVGW4->setStyleSheet(QString::fromUtf8(""));
        label_SIVGW1 = new QLabel(VersionInfoPage);
        label_SIVGW1->setObjectName(QString::fromUtf8("label_SIVGW1"));
        label_SIVGW1->setGeometry(QRect(162, 220, 190, 20));
        label_SIVGW1->setStyleSheet(QString::fromUtf8(""));

        retranslateUi(VersionInfoPage);

        QMetaObject::connectSlotsByName(VersionInfoPage);
    } // setupUi

    void retranslateUi(QWidget *VersionInfoPage)
    {
        VersionInfoPage->setWindowTitle(QApplication::translate("VersionInfoPage", "Form", 0, QApplication::UnicodeUTF8));
        label_HVAC->setText(QApplication::translate("VersionInfoPage", "HVAC", 0, QApplication::UnicodeUTF8));
        label_HMI1->setText(QString());
        label_car1Door1_1->setText(QApplication::translate("VersionInfoPage", "256.256", 0, QApplication::UnicodeUTF8));
        label_HMI4->setText(QString());
        label_AX1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_DI4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_SIV2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_AX2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_SIV4->setText(QString());
        label_HMI2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_AX4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_AX3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_car4Door1_1->setText(QString());
        label_DO1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_HVAC3->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_GW3->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_FAU2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_DO2->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_PIS->setText(QApplication::translate("VersionInfoPage", "PIS", 0, QApplication::UnicodeUTF8));
        label_DO3->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_HMI->setText(QApplication::translate("VersionInfoPage", "HMI", 0, QApplication::UnicodeUTF8));
        label_GW1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_ATC->setText(QApplication::translate("VersionInfoPage", "DOOR1", 0, QApplication::UnicodeUTF8));
        label_BCU1->setText(QString());
        label_PIS4->setText(QApplication::translate("VersionInfoPage", "0.0.0", 0, QApplication::UnicodeUTF8));
        label_DI2->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_PIS3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_BCU->setText(QApplication::translate("VersionInfoPage", "BCU", 0, QApplication::UnicodeUTF8));
        label_SIV->setText(QApplication::translate("VersionInfoPage", "SIV", 0, QApplication::UnicodeUTF8));
        label_car3Door1_1->setText(QString());
        label_DI1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_BCU2->setText(QString());
        label_AX->setText(QApplication::translate("VersionInfoPage", "AX", 0, QApplication::UnicodeUTF8));
        label_DO->setText(QApplication::translate("VersionInfoPage", "DO", 0, QApplication::UnicodeUTF8));
        label_FAU4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_HMI3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_DI3->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_DI->setText(QApplication::translate("VersionInfoPage", "DI", 0, QApplication::UnicodeUTF8));
        label_CCU2->setText(QString());
        label_PIS2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_CCU1->setText(QString());
        label_HVAC1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_FAU3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_FAU->setText(QApplication::translate("VersionInfoPage", "FAU", 0, QApplication::UnicodeUTF8));
        label_car2Door1_1->setText(QString());
        label_SIV1->setText(QString());
        label_DO4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_Door2->setText(QApplication::translate("VersionInfoPage", "DOOR2", 0, QApplication::UnicodeUTF8));
        label_GW2->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_DCU->setText(QApplication::translate("VersionInfoPage", "DCU", 0, QApplication::UnicodeUTF8));
        label_SIV3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_HVAC2->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        btn_back->setText(QApplication::translate("VersionInfoPage", "\350\277\224\345\233\236", 0, QApplication::UnicodeUTF8));
        label_GW->setText(QApplication::translate("VersionInfoPage", "IO\357\274\215GW", 0, QApplication::UnicodeUTF8));
        label_GW4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_HVAC4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_CCU->setText(QApplication::translate("VersionInfoPage", "CCU", 0, QApplication::UnicodeUTF8));
        label_FAU1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_PIS1->setText(QApplication::translate("VersionInfoPage", "0.0.0", 0, QApplication::UnicodeUTF8));
        label_ERM1->setText(QString());
        label_ERM->setText(QApplication::translate("VersionInfoPage", "ERM", 0, QApplication::UnicodeUTF8));
        label_ERM2->setText(QString());
        label_car1Door1_2->setText(QString());
        label_car1Door1_3->setText(QString());
        label_car1Door1_4->setText(QString());
        label_car2Door1_2->setText(QString());
        label_car2Door1_3->setText(QString());
        label_car2Door1_4->setText(QString());
        label_car3Door1_2->setText(QString());
        label_car3Door1_3->setText(QString());
        label_car3Door1_4->setText(QString());
        label_car4Door1_2->setText(QString());
        label_car4Door1_3->setText(QString());
        label_car4Door1_4->setText(QString());
        label_car4Door2_4->setText(QString());
        label_car2Door2_1->setText(QString());
        label_car3Door2_2->setText(QString());
        label_car1Door2_2->setText(QString());
        label_car3Door2_3->setText(QString());
        label_car4Door2_3->setText(QString());
        label_car4Door2_1->setText(QString());
        label_car2Door2_2->setText(QString());
        label_car4Door2_2->setText(QString());
        label_car1Door2_3->setText(QString());
        label_car1Door2_4->setText(QString());
        label_car2Door2_4->setText(QString());
        label_car2Door2_3->setText(QString());
        label_car3Door2_4->setText(QString());
        label_car1Door2_1->setText(QString());
        label_car3Door2_1->setText(QString());
        label_BCG1->setText(QApplication::translate("VersionInfoPage", "0.0.0", 0, QApplication::UnicodeUTF8));
        label_PDS2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_BMS4->setText(QString());
        label_PDS4->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_BCG4->setText(QApplication::translate("VersionInfoPage", "0.0.0", 0, QApplication::UnicodeUTF8));
        label_BCG3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_PDS->setText(QApplication::translate("VersionInfoPage", "PDS", 0, QApplication::UnicodeUTF8));
        label_BMS->setText(QApplication::translate("VersionInfoPage", "BMS", 0, QApplication::UnicodeUTF8));
        label_BMS3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_BMS1->setText(QString());
        label_BCG2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_BCG->setText(QApplication::translate("VersionInfoPage", "BCG", 0, QApplication::UnicodeUTF8));
        label_PDS1->setText(QApplication::translate("VersionInfoPage", "0.0", 0, QApplication::UnicodeUTF8));
        label_BMS2->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_PDS3->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_car2DCU2->setText(QString());
        label_car2DCU4->setText(QString());
        label_car1DCU->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_car4DCU->setText(QApplication::translate("VersionInfoPage", "-- -- ", 0, QApplication::UnicodeUTF8));
        label_car3DCU4->setText(QString());
        label_car2DCU1->setText(QString());
        label_car3DCU1->setText(QString());
        label_car3DCU3->setText(QString());
        label_car2DCU3->setText(QString());
        label_car3DCU2->setText(QString());
        label_car2DCUGW->setText(QString());
        label_car3DCUGW->setText(QString());
        label_SIVGW4->setText(QString());
        label_SIVGW1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class VersionInfoPage: public Ui_VersionInfoPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VERSIONINFOPAGE_H
